config/routes.rb
Rails.application.routes.draw do
  
  root 'tops#index'

  resources :users
  
  resources :sessions
  
  resources :favorites, only: [:create, :destroy]
  
  resources :events do
    collection do
      post :confirm
    end
  end
  get '/events', to: 'events#index'
  
  get '/caught_fishes/new/:event_id', to: 'caught_fishes#new', as: 'new_caught_fish'
  get '/caught_fishes/:event_id', to: 'caught_fishes#index', as: 'caught_fishes'
  get '/caught_fishes/:event_id/:id', to: 'caught_fishes#show', as: 'caught_fish'
  get '/caught_fishes/:event_id/:id/edit', to: 'caught_fishes#edit', as: 'edit_caught_fish'
  post '/caught_fishes/:event_id', to: 'caught_fishes#create', as: 'create_caught_fish'
  delete '/caught_fishes/:event_id/:id', to: 'caught_fishes#destroy', as: 'destroy_caught_fish'
  patch '/caught_fishes/:event_id/:id', to: 'caught_fishes#update', as: 'update_caught_fish'

  resources :tops do
  end
  
end

app/models/caught_fish.rb
class CaughtFish < ApplicationRecord
  belongs_to :event
  has_many :fish_images, dependent: :destroy
  accepts_nested_attributes_for :fish_images
  validates :name, presence: true
  validates :caught_number, presence: true
  validates :caught_number, numericality: true
end

app/controllers/caught_fishes_controller.rb
class CaughtFishesController < ApplicationController
  include SessionsHelper
  before_action :set_event, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  before_action :current_user, only: [:new, :show, :edit, :destroy]
  before_action :set_caught_fish, only: [:edit, :update, :destroy]
  
  def index
    logger.debug("Debug into caught_fish index 1 -----")
    
    if !logged_in?
      redirect_to new_session_path
    end
    @caught_fishes = CaughtFish.where(event_id: @event.id)
    #binding.pry # ブレークポイントを設定
  end

  def new
    logger.debug("Debug into caught_fish new 1 -----")
    
    if !logged_in?
      redirect_to new_session_path
    end
  
    if params[:back]
      @caught_fish = CaughtFish.new(caught_fish_params)
      @caught_fish.event_id = @event.id
      
      if !params[:cache].nil? && params[:cache][:image].present?
        # Feedテーブルの中に、imageのカラム（画像アップロード用のカラム）以外のものがある場合、
        # Feed.newではなくFeed.new(feed_params)にする。
        @fish_images = FishImage.new(fish_image_params)
        # 画像保存（create）の際に、キャッシュから画像を復元してnewに入れる
        # newに戻る際も、createと同様に復元処理が必要となる。
        @fish_image.image.retrieve_from_cache! params[:cache][:image]
      end
      
    else
      @caught_fish = CaughtFish.new
      @fish_image = FishImage.new()
      @submit = '登録'
    end

  logger.debug("Debug caught_fish new2-----")
  logger.debug(@caught_fish)
  logger.debug(@fish_image)

  end
  
  def create
    logger.debug("Debug into caught_fish create 1 -----")
    @caught_fish = CaughtFish.new(caught_fish_params)
    @caught_fish.event_id = @event.id
    @caught_fish.caught_number = params[:caught_fish][:caught_number].tr('０-９', '0-9')

    #binding.pry # ブレークポイントを設定
    logger.debug("Debug caught_fish create1-----")
    logger.debug(@event)
    logger.debug(@caught_fish)
    logger.debug(@fish_image)
    
    if !params[:caught_fish].nil? && params[:caught_fish][:fish_image][:image].present?
      
      logger.debug("Debug fish_image create-----")
      @fish_image = FishImage.new({:image => params[:caught_fish][:fish_image][:image]})
      logger.debug("Debug caught_fish create2-----")
      logger.debug(@fish_image)
      #@fish_image.image.retrieve_from_cache! params[:cache][:image]
    end

    if @caught_fish.save
      #binding.pry # ブレークポイントを設定
      if !params[:caught_fish].nil? && params[:caught_fish][:fish_image][:image].present?
        @fish_image.event_id = @caught_fish.event_id
        @fish_image.caught_fish_id = @caught_fish.id
        @fish_image.save
      end
      
      # 一覧画面へ遷移して"釣果を登録しました！"とメッセージを表示します。
      redirect_to caught_fishes_path, notice: "釣果を登録しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
    
  end
  
  def show
    logger.debug("Debug into caught_fish show 1 -----")
    if !logged_in?
      redirect_to new_session_path
    end
    redirect_to caught_fishes_path
  end
  
  def edit
    logger.debug("Debug into caught_fish edit 1 -----")
    if !logged_in?
      redirect_to new_session_path
    end
    @fish_images = @caught_fish.fish_images.where(caught_fish_id: @caught_fish.id)
    @submit = '更新'
  end
  
  def update
    logger.debug("Debug into caught_fish update 1 -----")
    #binding.pry # ブレークポイントを設定
    if !params[:caught_fish].nil? && params[:caught_fish][:fish_image][:image].present?
      
      logger.debug("Debug fish_image create-----")
      @fish_image = FishImage.new({:image => params[:caught_fish][:fish_image][:image]})
      logger.debug("Debug caught_fish create2-----")
      logger.debug(@fish_image)
      #@fish_image.image.retrieve_from_cache! params[:cache][:image]
    end
    
    if @caught_fish.update(caught_fish_params)
      #binding.pry # ブレークポイントを設定
      if !params[:caught_fish].nil? && params[:caught_fish][:fish_image][:image].present?
        @fish_image.event_id = @caught_fish.event_id
        @fish_image.caught_fish_id = @caught_fish.id
        @fish_image.save
      end
      
      redirect_to caught_fishes_path, notice: "釣果を更新しました！"
    else
      redirect_to edit_caught_fish_path(@event,id: @caught_fish.id)
      #render 'edit'
    end
  end
  
  def destroy
    if !logged_in?
      redirect_to new_session_path
    end
    @caught_fish.destroy
    redirect_to caught_fishes_path, notice:"釣果を削除しました！"
  end
  
#  def confirm
#    @caught_fish = CaughtFish.new(caught_fish_params)
#    @caught_fish.event_id = @event.id
#    
#    logger.debug("Debug caught_fish confirm-----")
#    logger.debug(@caught_fish)
#    @fish_image = FishImage.new(fish_image_params)
#    
#    logger.debug("Debug fish_image confirm-----")
#    logger.debug(@fish_image)
#
#    render :new if @caught_fish.invalid?
#  end
  
  private
  def caught_fish_params
    params.require(:caught_fish).permit(:name,
    :size, :weight, 
    :tackle, :bait, 
    :caught_number, :caught_time,
    :description,
    fish_image_attributes: [:image,  :image_cache]
    )
  end
  
  def fish_image_params
    params.require(:fish_image).permit(:image, :image_cache)
  end

  
  private
  def set_event
    @event = Event.find(params[:event_id])
  end
  
  private
  def set_caught_fish
    @caught_fish = CaughtFish.find(params[:id])
  end
  
end

app/helpers/caught_fishes_helper.rb
module CaughtFishesHelper
  def caught_fish_choose_new_or_edit
    logger.debug("Debug into caught_fish_choose_new_or_edit 1 -----")
    if action_name == 'new'
      create_caught_fish_path(@event)
    elsif action_name == 'edit'
      logger.debug("Debug into caught_fish_choose_new_or_edit edit 1 -----")
      update_caught_fish_path(@event, id: @caught_fish.id)
    end
  end
end

app/views/caught_fishes/_form.html.erb
<div class="col-xs-12 col-md-6 event-panel input-caught_fish-box">
  
  <%= form_with(model: @caught_fish, local: true ,url: caught_fish_choose_new_or_edit ) do |form| %>
    <% if @caught_fish.errors.any? %>
    <div id="error_explanation">
        <h2><%= @caught_fish.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @caught_fish.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <ul>
      <li>
        <div class="caught_fish_caught_time">
          <%= form.label :caught_time, "釣った時刻：" %>
          <%= form.text_field :caught_time %>
        </div>
      </li>
      <li>
        <div class="caught_fish_name">
          <%= form.label :name, "魚の名前：" %>
          <%= form.text_field :name %>
        </div>
      </li>
      <li>
        <div class="caught_fish_size">
          <%= form.label :size, "サイズ：" %>
          <%= form.text_field :size %>
        </div>
      </li>
      <li>
        <div class="caught_fish_weight">
          <%= form.label :weight, "重さ：" %>
          <%= form.text_field :weight %>
        </div>
      </li>
      <li>
        <div class="caught_fish_tackle">
          <%= form.label :tackle, "タックル：" %>
          <%= form.text_field :tackle %>
        </div>
      </li>
      <li>
        <div class="caught_fish_bait">
          <%= form.label :bait, "エサ：" %>
          <%= form.text_field :bait %>
        </div>
      </li>
      <li>
        <div class="caught_fish_caught_number">
          <%= form.label :caught_number, "釣った数：" %>
          <%= form.text_field :caught_number %>
        </div>
      </li>
    </ul>

    <%= form.fields_for :fish_image do |fish_image_field| %>
      <ul>
        <li>
          <div class="fish_image">
            <%= fish_image_field.label :image, "写真の追加：" %>
            <%= fish_image_field.file_field :image, id: :fish_image %>
            <%= fish_image_field.hidden_field :image_cache %>
          </div>
        </li>
      </ul>
    <% end %>

    <div class="fish_images">
      <% if FishImage.where(caught_fish_id: @caught_fish.id).exists? %>
        <% @fish_images.each do |fish_image| %>
          <ul>
            <li>
              <strong></strong>
              <%= image_tag fish_image.image %>
            </li>
          </ul>
        <% end %>
      <% end %>
    </div>
  
  
    <%= form.submit @submit %>
  <% end %>
  <br>
  <%= link_to 'もどる', caught_fishes_path(@event), class: 'btn btn-primary'%>

</div>

app/views/caught_fishes/confirm.html.erb
<u><h3>以下の内容で、送信する</h3></u>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog_image.image) %>
  <%= hidden_field_tag :"cache[image]",@blog_image.image.cache_name %>
  <%= form.submit  "登録する" %>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= hidden_field_tag :"cache[image]",@blog_image.image.cache_name %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/caught_fishes/edit.html.erb
<div class="container">
  <u><h2>釣果を編集する</h2></u>

  <%= render 'form' %>

</div>

app/views/caught_fishes/index.html.erb
<div class="container">
  <u><h2>釣果の一覧</h2></u>
  <h3>釣り場所:<%= @event.spot_name %></h3>
  <h3>開始日:<%= @event.start_date.strftime("%Y-%m-%d") %></h3>
  
  <% if @event.user_id == current_user.id %>
    <div id="new-caught_fish-link" class="new-caught_fish-box">
      <%= link_to '釣果を追加する', new_caught_fish_path %>
    </div>
  <% end %>
  
  <% @caught_fishes.each do |caught_fish| %>
    <div class="col-xs-12 col-md-6 caught_fish-panel caught_fish-box">
      <div class="caught_fish-panel">
        <div class="caught_fish-links">
          <% if @event.user_id == current_user.id %>
            <%= link_to '編集', edit_caught_fish_path(@event,id: caught_fish.id), class: 'btn btn-info' %> |
            <%= link_to '削除', destroy_caught_fish_path(@event,id: caught_fish.id), method: :delete, data: { confirm: '本当に削除しますか?' }, class: 'btn btn-danger' %>
          <% end %>
        </div>

        <p>釣った時刻：<%= caught_fish.caught_time %></p>
        <p>魚の名前：<%= caught_fish.name %></p>
        <p>サイズ：<%= caught_fish.size %></p>
        <p>重さ：<%= caught_fish.weight %></p>
        <p>タックル：<%= caught_fish.tackle %></p>
        <p>エサ：<%= caught_fish.bait %></p>
        <p>釣った数：<%= caught_fish.caught_number %></p>
        <p>
          <% if FishImage.where(caught_fish_id: caught_fish.id).exists? %>
            <% @fish_images = FishImage.where(caught_fish_id: caught_fish.id) %>
            <% @fish_images.each do |fish_image| %>
              <ul>
                <li>
                  <strong></strong>
                  <%= image_tag fish_image.image %>
                </li>
              </ul>
            <% end %>
          <% end %>
        </p>
      </div>
    </div>
  <% end %>

</div>

app/views/caught_fishes/new.html.erb
<div class="container">
  <u><h2>釣果を登録する</h2></u>
  
  <%= render 'form' %>
</div>

app/views/caught_fishes/show.html.erb
<u><h2>釣果詳細画面</h2></u>