config/routes.rb
Rails.application.routes.draw do
  
  root 'tops#index'

  resources :users
  
  resources :sessions
  
  resources :favorites, only: [:create, :destroy]
  
  resources :events do
    collection do
      post :confirm
    end
  end
  get '/events', to: 'events#index'
  
  get '/caught_fishes/new/:event_id', to: 'caught_fishes#new', as: 'new_caught_fish'
  get '/caught_fishes/:event_id', to: 'caught_fishes#index', as: 'caught_fishes'
  get '/caught_fishes/:event_id/:id', to: 'caught_fishes#show', as: 'caught_fish'
  get '/caught_fishes/:event_id/:id/edit', to: 'caught_fishes#edit', as: 'edit_caught_fish'
  post '/caught_fishes/:event_id', to: 'caught_fishes#create', as: 'create_caught_fish'
  delete '/caught_fishes/:event_id/:id', to: 'caught_fishes#destroy', as: 'destroy_caught_fish'
  patch '/caught_fishes/:event_id/:id', to: 'caught_fishes#update', as: 'update_caught_fish'

  resources :tops do
  end
  
end

app/models/event.rb
class Event < ApplicationRecord
  include SearchCop
  
  search_scope :search do
    attributes :spot_name, :start_date, :end_date, :target, :method, :tackle, :bait, :description
    attributes event_option: ['event_option.weather', 'event_option.tide']
    attributes caught_fish: ['caught_fishes.name', 'caught_fishes.tackle', 'caught_fishes.bait']
  end
  
  belongs_to :user
  has_one :event_option, dependent: :destroy
  accepts_nested_attributes_for :event_option
  has_many :caught_fishes, dependent: :destroy
  accepts_nested_attributes_for :caught_fishes
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :spot_name, presence: true
  validates :start_date, presence: true
  validates :method, presence: true
  validates :target, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include SessionsHelper
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :current_user, only: [:new, :show, :edit, :destroy]
  
  def index
    if params[:search]
      #binding.pry # ブレークポイントを設定
      @events = Event.search(params[:search])
      logger.debug("Debug into search-----")
      logger.debug(@event)
    else
      @events = Event.all
      logger.debug("Debug out of search-----")
      logger.debug(@event)
    end
    
  end

  def new
    if !logged_in?
      redirect_to new_session_path
    end
    if params[:back]
      @event = Event.new(event_params)
      #@event_option = EventOption.new(event_option_params)
      
      #binding.pry # ブレークポイントを設定
    else
      @event = Event.new
      #@event_option = EventOption.new()
    end
    @submit = '確認'
    #binding.pry # ブレークポイントを設定
    #@event.build_event_option
    @event.user = current_user

  logger.debug("Debug event new-----")
  logger.debug(@event)
  logger.debug(@event.user)

  end
  
  def create
    @event = Event.new(event_params)
    #@event_option = EventOption.new(event_option_params)
    #@event.build_event_option
    @event.user = current_user
    
    #binding.pry # ブレークポイントを設定
    logger.debug("Debug event create-----")
    logger.debug(@event)
    logger.debug(@event.user)
    
    if @event.save
      #@event_option.event_id = @event.id
      #@event_option.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to events_path, notice: "日記を作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
    
  end
  
  def show
    if !logged_in?
      redirect_to new_session_path
    end
    @favorite = current_user.favorites.find_by(event_id: @event.id)
  end
  
  def edit
    if !logged_in?
      redirect_to new_session_path
    end
    @submit = '更新'
    @event.start_date = @event.start_date.strftime("%Y-%m-%d")
    unless @event.end_date.blank?
      @event.end_date = @event.end_date.strftime("%Y-%m-%d")
    end
    #@event_option = @event.event_options.find_by(event_id: @event.id)
  end
  
  def update
    if @event.update(event_params)
      redirect_to events_path, notice: "日記を編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    if !logged_in?
      redirect_to new_session_path
    end
    @event.destroy
    redirect_to events_path, notice:"日記を削除しました！"
  end
  
  def confirm
    @event = Event.new(event_params)
    @event.user = current_user
    
    #@event.build_event_option(event_params)
    
    #binding.pry # ブレークポイントを設定
    logger.debug("Debug event confirm-----")
    logger.debug(@event)
    logger.debug(@event.user)
    logger.debug(@event.event_option)
    logger.debug(@event.event_option.weather)
    logger.debug(@event.event_option.first_low_tide)

    @submit = '登録'
    render :new if @event.invalid?
  end
  
  private
  def event_params
    params.require(:event).permit(:spot_name,
    :start_date, :end_date, 
    :method, :target, :tackle, :bait, 
    :description,
    event_option_attributes: [:weather, 
    :max_temperature, :min_temperature, 
    :wind_speed, :wind_direction, 
    :wave_height,
    :location_latitude, :location_longitude, 
    :tide, :first_low_tide, :first_high_tide, :second_low_tide, :second_high_tide]
    )
  end
  
  def event_option_params
    params.require(:event_option).permit(:weather, :max_temperature, :min_temperature, :wind_speed, :wind_direction, :wave_height,
    :location_latitude, :location_longitude, :tide, :first_low_tide, :first_high_tide, :second_low_tide, :second_high_tide)
  end

  
  private
  def set_event
    @event = Event.find(params[:id])
  end


end

app/helpers/events_helper.rb
module EventsHelper
  def event_choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_events_path
    elsif action_name == 'edit'
      event_path
    end
  end
end

app/views/events/_form.html.erb
<div class="col-xs-12 col-md-6 event-panel input-event-box">

  <%= form_with(model: @event, local: true ,url: event_choose_new_or_edit ) do |form| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= @event.errors.count %>件のエラーがあります。</h2>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <ul>
      <li>
        <div class="event_spot_name">
          <%= form.label :spot_name, "釣り場所：" %>
          <%= form.text_field :spot_name %>
        </div>
      </li>
      <li>
        <div class="event_start_date">
          <%= form.label :start_date, "開始日：" %>
          <%= form.text_field :start_date, class: 'start-date-picker' %>
        </div>
      </li>
      <li>
        <div class="event_end_date">
          <%= form.label :end_date, "終了日：" %>
          <%= form.text_field :end_date, class: 'end-date-picker' %>
        </div>
      </li>
      <li>
        <div class="event_method">
          <%= form.label :method, "釣り方：" %>
          <%= form.text_field :method %>
        </div>
      </li>
      <li>
        <div class="event_target">
          <%= form.label :target, "狙う魚：" %>
          <%= form.text_field :target %>
        </div>
      </li>
      <li>
        <div class="event_tackle">
          <%= form.label :tackle, "タックル：" %>
          <%= form.text_field :tackle %>
        </div>
      </li>
      <li>
        <div class="event_bait">
          <%= form.label :bait, "餌：" %>
          <%= form.text_field :bait %>
        </div>
      </li>
      <li>
        <div class="event_description">
          <%= form.label :description, "感想：" %>
          <%= form.text_field :description %>
        </div>
      </li>
    </ul>
  
    
    <%= form.fields_for :event_option, @event.event_option || EventOption.new do |event_option_form| %>
      <ul>
        <li>
          <div class="event_option_weather">
            <%= event_option_form.label :weather, "天気：" %>
            <%= event_option_form.text_field :weather %>
          </div>
        </li>
      </ul>
      <ul>
        <li>
          <div class="event_option_tide">
            <%= event_option_form.label :tide, "潮：" %>
            <%= event_option_form.select :tide, 
              [["不明", "不明"],
              ["大潮", "大潮"],
              ["中潮", "中潮"],
              ["小潮", "小潮"],
              ["長潮", "長潮"],
              ["若潮", "若潮"]]
            %>
          </div>
        </li>
      </ul>
      
      <br>
      <br>
      <ul>
        <div class="event_option_temperature">
          <li>
            <%= event_option_form.label :max_temperature, "最高気温：" %>
            <%= event_option_form.text_field :max_temperature %>
          </li>
          <li>
            <%= event_option_form.label :min_temperature, "最低気温：" %>
            <%= event_option_form.text_field :min_temperature %>
          </li>
        </div>
      </ul>

      <ul>
        <div class="event_option_wind">
          <li>
            <%= event_option_form.label :wind_speed, "風速：" %>
            <%= event_option_form.text_field :wind_speed %>
          </li>
          <li>
            <%= event_option_form.label :wind_direction, "風向き：" %>
            <%= event_option_form.select :wind_direction, 
              [["不明", "不明"],
              ["東", "東"],
              ["西", "西"],
              ["南", "南"],
              ["北", "北"],
              ["北東", "北東"],
              ["北西", "北西"],
              ["南東", "南東"],
              ["南西", "南西"],
              ["北北東", "北北東"],
              ["北北西", "北北西"],
              ["南南東", "南南東"],
              ["南南西", "南南西"],
              ["東北東", "東北東"],
              ["西北西", "西北西"],
              ["東南東", "東南東"],
              ["西南西", "西南西"]]
            %>
          </li>
        </div>
      </ul>
      
      <br>
      <ul>
        <li>
          <div class="event_option_wave">
            <%= event_option_form.label :wave_height, "波の高さ：" %>
            <%= event_option_form.text_field :wave_height %>
          </div>
        </li>
      </ul>
      
      <ul>
        <div class="event_option_first_tide">
          <li>
            <%= event_option_form.label :first_low_tide, "干潮時刻１：" %>
            <div class='input-group date timepicker'>
              <span class="input-group-addon">
                <span class="fa fa-clock-o"></span>
              </span>
              <%= event_option_form.text_field :first_low_tide,
                class: 'form-control', style: "width: 192px" %>
            </div>
          </li>
          <li>
            <%= event_option_form.label :first_high_tide, "満潮時刻１：" %>
            <div class='input-group date timepicker'>
              <span class="input-group-addon">
                <span class="fa fa-clock-o"></span>
              </span>
              <%= event_option_form.text_field :first_high_tide,
                class: 'form-control', style: "width: 192px" %>
            </div>
          </li>
        </div>
        
      </ul>
      <ul>
        <div class="event_option_second_tide">
          <li>
            <%= event_option_form.label :second_low_tide, "干潮時刻２：" %>
            <div class='input-group date timepicker'>
              <span class="input-group-addon">
                <span class="fa fa-clock-o"></span>
              </span>
              <%= event_option_form.text_field :second_low_tide,
                class: 'form-control', style: "width: 192px" %>
            </div>
          </li>
          <li>
            <%= event_option_form.label :second_high_tide, "満潮時刻２：" %>
            <div class='input-group date timepicker'>
              <span class="input-group-addon">
                <span class="fa fa-clock-o"></span>
              </span>
              <%= event_option_form.text_field :second_high_tide,
                class: 'form-control', style: "width: 192px" %>
            </div>
          </li>
        </div>
      </ul>
    <% end %>
    
    <%= form.submit @submit %>
  <% end %>
  <br>
  <%= link_to 'もどる', '/events', class: 'btn btn-primary'%>

</div>

app/views/events/confirm.html.erb
<div class="container">
<u><h3>以下の内容で、送信する。</h3></u>

<div class="col-xs-12 col-md-6 event-panel show-event-box">
<%= form_with(model: @event, url: events_path, local: true) do |form| %>
  <%= form.hidden_field :spot_name %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>
  <%= form.hidden_field :method %>
  <%= form.hidden_field :target %>
  <%= form.hidden_field :tackle %>
  <%= form.hidden_field :bait %>
  <%= form.hidden_field :description %>
  
  <%= form.fields_for :event_option, @event.event_option || EventOption.new do |event_option_form| %>
    <%= event_option_form.hidden_field :weather %>
    <%= event_option_form.hidden_field :tide %>
    <%= event_option_form.hidden_field :max_temperature %>
    <%= event_option_form.hidden_field :min_temperature %>
    <%= event_option_form.hidden_field :wind_speed %>
    <%= event_option_form.hidden_field :wind_direction %>
    <%= event_option_form.hidden_field :wave_height %>
    <%= event_option_form.hidden_field :first_low_tide %>
    <%= event_option_form.hidden_field :first_high_tide %>
    <%= event_option_form.hidden_field :second_low_tide %>
    <%= event_option_form.hidden_field :second_high_tide %>
  <% end %>
  
  <p>釣り場所：<%= @event.spot_name %></p>
  <p>開始日：<%= @event.start_date.strftime("%Y-%m-%d")  %></p>
  <% unless @event.end_date.blank? %>
    <p>終了日：<%= @event.end_date.strftime("%Y-%m-%d") %></p>
  <% else %>
    <p>終了日：<%= @event.end_date %></p>
  <% end %>
  <p>釣り方：<%= @event.method %></p>
  <p>狙う魚：<%= @event.target %></p>
  <p>タックル：<%= @event.tackle %></p>
  <p>餌：<%= @event.bait %></p>
  <p>説明：<%= @event.description %></p>
  
  <p>天気：<%= @event.event_option.weather %></p>
  <p>潮：<%= @event.event_option.tide %></p>
  <p>最高気温：<%= @event.event_option.max_temperature %></p>
  <p>最低気温：<%= @event.event_option.min_temperature %></p>
  <p>風速：<%= @event.event_option.wind_speed %></p>
  <p>風向き：<%= @event.event_option.wind_direction %></p>
  <p>波の高さ：<%= @event.event_option.wave_height %></p>
  <p>干潮時刻１：<%= @event.event_option.first_low_tide %></p>
  <p>満潮時刻１：<%= @event.event_option.first_high_tide %></p>
  <p>干潮時刻２：<%= @event.event_option.second_low_tide %></p>
  <p>満潮時刻２：<%= @event.event_option.second_high_tide %></p>
 
  <%= form.submit  "登録" %>
<% end %>

<%= form_with(model: @event, url: new_event_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :spot_name %>
  <%= form.hidden_field :start_date %>
  <%= form.hidden_field :end_date %>
  <%= form.hidden_field :method %>
  <%= form.hidden_field :target %>
  <%= form.hidden_field :tackle %>
  <%= form.hidden_field :bait %>
  <%= form.hidden_field :description %>
  
  <%= form.fields_for :event_option, @event.event_option || EventOption.new do |event_option_form| %>
    <%= event_option_form.hidden_field :weather %>
    <%= event_option_form.hidden_field :tide %>
    <%= event_option_form.hidden_field :max_temperature %>
    <%= event_option_form.hidden_field :min_temperature %>
    <%= event_option_form.hidden_field :wind_speed %>
    <%= event_option_form.hidden_field :wind_direction %>
    <%= event_option_form.hidden_field :wave_height %>
    <%= event_option_form.hidden_field :first_low_tide %>
    <%= event_option_form.hidden_field :first_high_tide %>
    <%= event_option_form.hidden_field :second_low_tide %>
    <%= event_option_form.hidden_field :second_high_tide %>
  <% end %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>
</div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <% content_for(:body_attributes) do %>
    data-turbolinks="false"
  <% end %>

  <u><h2>釣り日記を編集する</h2></u>

  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="container">
  <u><h2>釣り日記の一覧</h2></u>
  <div id="new-event-link" class="new-event-box">
    <%= link_to '新規釣り日記を作成する', new_event_path %>
  </div>
  
  <div id="new-event-link" class="search-event-box">
    <%= form_tag(events_path, method: :get) do %> 
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "日記の検索", :name => nil %>
      </p>
    <% end %>
  </div>

  <% @events.each do |event| %>
    <div class="col-xs-12 col-md-6 event-panel event-box">
      <div class="event-panel">
        <p>釣り場所：<%= event.spot_name %></p>
        <p>開始日：<%= event.start_date.strftime("%Y-%m-%d") %></p>
        <% unless event.end_date.blank? %>
          <p>終了日：<%= event.end_date.strftime("%Y-%m-%d") %></p>
        <% else %>
          <p>終了日：<%= event.end_date %></p>
        <% end %>
        <p>釣り方：<%= event.method %></p>
        <p>狙う魚：<%= event.target %></p>
        <p>タックル：<%= event.tackle %></p>
        <p>餌：<%= event.bait %></p>
        <p>感想：<%= event.description %></p>

        <div class="event-links" data-no-turbolink>
          <% if logged_in? %>
            <%= link_to '詳細', event, class: 'btn btn-default' %>
            <%= link_to '釣果', caught_fishes_path(event), class: 'btn btn-default'  %>
            <% if event.user_id == current_user.id %>
              <%= link_to '編集', edit_event_path(event), class: 'btn btn-info' %> |
              <%= link_to '削除', event, method: :delete, data: { confirm: '本当に削除しますか?' }, class: 'btn btn-danger' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/events/new.html.erb
<div class="container">
  <u><h2>釣り日記を作成する</h2></u>

  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="container">
  <u><h2>釣り日記詳細</h2></u>

  <div class="col-xs-12 col-md-6 event-panel show-event-box">
    <p>作成者： <%= @event.user.name %></p>

    <p>釣り場所：<%= @event.spot_name %></p>
    <p>開始日：<%= @event.start_date.strftime("%Y-%m-%d") %></p>
    <% unless @event.end_date.blank? %>
      <p>終了日：<%= @event.end_date.strftime("%Y-%m-%d") %></p>
    <% else %>
      <p>終了日：<%= @event.end_date %></p>
    <% end %>
    
    <p>釣り方：<%= @event.method %></p>
    <p>狙う魚：<%= @event.target %></p>
    <p>タックル：<%= @event.tackle %></p>
    <p>餌：<%= @event.bait %></p>
    <p>説明：<%= @event.description %></p>
  
    <p>天気：<%= @event.event_option.weather %></p>
    <p>潮：<%= @event.event_option.tide %></p>
    <p>最高気温：<%= @event.event_option.max_temperature %></p>
    <p>最低気温：<%= @event.event_option.min_temperature %></p>
    <p>風速：<%= @event.event_option.wind_speed %></p>
    <p>風向き：<%= @event.event_option.wind_direction %></p>
    <p>波の高さ：<%= @event.event_option.wave_height %></p>
    <p>干潮時刻１：<%= @event.event_option.first_low_tide %></p>
    <p>満潮時刻１：<%= @event.event_option.first_high_tide %></p>
    <p>干潮時刻２：<%= @event.event_option.second_low_tide %></p>
    <p>満潮時刻２：<%= @event.event_option.second_high_tide %></p>

    <%= link_to '釣り日記一覧画面にもどる', events_path, class: 'btn btn-primary' %>


    <% if @event.user_id == @current_user.id %>
      <%= link_to "釣り日記を編集する", edit_event_path(@event.id), class: 'btn btn-primary' %>
    <% else %>
      <% if @favorite.present? %>
        <%= link_to 'お気に入り解除する', favorite_path(event_id: @event.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'お気に入りする', favorites_path(event_id: @event.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
    <% end %>
  </div>
</div>