config/routes.rb
Rails.application.routes.draw do
  
  root 'tops#index'

  resources :users
  
  resources :sessions
  
  resources :favorites, only: [:create, :destroy]
  
  resources :events do
    collection do
      post :confirm
    end
  end
  get '/events', to: 'events#index'
  
  get '/caught_fishes/new/:event_id', to: 'caught_fishes#new', as: 'new_caught_fish'
  get '/caught_fishes/:event_id', to: 'caught_fishes#index', as: 'caught_fishes'
  get '/caught_fishes/:event_id/:id', to: 'caught_fishes#show', as: 'caught_fish'
  get '/caught_fishes/:event_id/:id/edit', to: 'caught_fishes#edit', as: 'edit_caught_fish'
  post '/caught_fishes/:event_id', to: 'caught_fishes#create', as: 'create_caught_fish'
  delete '/caught_fishes/:event_id/:id', to: 'caught_fishes#destroy', as: 'destroy_caught_fish'
  patch '/caught_fishes/:event_id/:id', to: 'caught_fishes#update', as: 'update_caught_fish'

  resources :tops do
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fishingdiary</title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if content_for?(:body_attributes) %>
      <%= yield(:body_attributes) %>
    <% end %>>
    <header>
      <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">釣り日記β</span>
              Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="/tops/">釣り日記β</a>
          </div>
          <!-- /.navbar-header -->
          
          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to '釣り日記', events_path %></li>
              <% if logged_in? %>
                <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
              <% else %>
                <li><%= link_to "サインアップ", new_user_path %></li>
                <li><%= link_to "ログイン", new_session_path %></li>
              <% end %>
            </ul>
          </div>
          <!-- /.navbar-collapse -->
          
        </div>
        <!-- /.container -->
      </nav>
    </header>
    
    <%= yield %>
    
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>柴田喜匡が勉強してます</p>
            <p>© 2017-2018 Copyright Yoshimasa Shibata</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>